name: selecta_coee
description: SELECTA-COE - Student Electronic Ledger & Competency Tracker

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  intl: ^0.20.2
  image_picker: ^1.2.2
  font_awesome_flutter: ^11.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.1.1
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  firebase_auth: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/LOGO.png
  adaptive_icon_background: "#F9FAFB"
  adaptive_icon_foreground: assets/LOGO.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/LOGO.png
    background_color: "#F9FAFB"
    theme_color: "#C8102E"
  windows:
    generate: true
    image_path: assets/LOGO.png
    icon_size: 256
  macos:
    generate: true
    image_path: assets/LOGO.png

flutter:
  uses-material-design: true
  assets:
    - assets/LOGO.png
